spring.application.name=SpringBootDataJDBCRestPrac

spring.datasource.url=jdbc:mysql://localhost:3306/springJDBC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver